# CMake generated Testfile for 
# Source directory: /home/saifmulla/openmm/OpenMM/platforms/reference/tests
# Build directory: /home/saifmulla/openmm/OpenMM/platforms/reference/tests
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(TestReferenceNeighborList "/home/saifmulla/openmm/OpenMM/TestReferenceNeighborList")
ADD_TEST(TestReferenceAndersenThermostat "/home/saifmulla/openmm/OpenMM/TestReferenceAndersenThermostat")
ADD_TEST(TestReferenceHarmonicAngleForce "/home/saifmulla/openmm/OpenMM/TestReferenceHarmonicAngleForce")
ADD_TEST(TestReferenceRandom "/home/saifmulla/openmm/OpenMM/TestReferenceRandom")
ADD_TEST(TestReferenceVariableLangevinIntegrator "/home/saifmulla/openmm/OpenMM/TestReferenceVariableLangevinIntegrator")
ADD_TEST(TestReferenceCustomAngleForce "/home/saifmulla/openmm/OpenMM/TestReferenceCustomAngleForce")
ADD_TEST(TestReferenceHarmonicBondForce "/home/saifmulla/openmm/OpenMM/TestReferenceHarmonicBondForce")
ADD_TEST(TestReferenceNonbondedForce "/home/saifmulla/openmm/OpenMM/TestReferenceNonbondedForce")
ADD_TEST(TestReferenceCustomTorsionForce "/home/saifmulla/openmm/OpenMM/TestReferenceCustomTorsionForce")
ADD_TEST(TestReferenceCMAPTorsionForce "/home/saifmulla/openmm/OpenMM/TestReferenceCMAPTorsionForce")
ADD_TEST(TestReferenceVariableVerletIntegrator "/home/saifmulla/openmm/OpenMM/TestReferenceVariableVerletIntegrator")
ADD_TEST(TestReferenceCustomExternalForce "/home/saifmulla/openmm/OpenMM/TestReferenceCustomExternalForce")
ADD_TEST(TestReferenceGBVIForce "/home/saifmulla/openmm/OpenMM/TestReferenceGBVIForce")
ADD_TEST(TestReferenceLangevinIntegrator "/home/saifmulla/openmm/OpenMM/TestReferenceLangevinIntegrator")
ADD_TEST(TestReferenceLocalEnergyMinimizer "/home/saifmulla/openmm/OpenMM/TestReferenceLocalEnergyMinimizer")
ADD_TEST(TestReferenceEwald "/home/saifmulla/openmm/OpenMM/TestReferenceEwald")
ADD_TEST(TestReferenceRBTorsionForce "/home/saifmulla/openmm/OpenMM/TestReferenceRBTorsionForce")
ADD_TEST(TestReferenceVelocityVerletIntegrator "/home/saifmulla/openmm/OpenMM/TestReferenceVelocityVerletIntegrator")
ADD_TEST(TestReferenceBrownianIntegrator "/home/saifmulla/openmm/OpenMM/TestReferenceBrownianIntegrator")
ADD_TEST(TestReferenceCustomGBForce "/home/saifmulla/openmm/OpenMM/TestReferenceCustomGBForce")
ADD_TEST(TestReferenceGBSAOBCForce "/home/saifmulla/openmm/OpenMM/TestReferenceGBSAOBCForce")
ADD_TEST(TestReferenceCustomHbondForce "/home/saifmulla/openmm/OpenMM/TestReferenceCustomHbondForce")
ADD_TEST(TestReferenceKineticEnergy "/home/saifmulla/openmm/OpenMM/TestReferenceKineticEnergy")
ADD_TEST(TestReferenceCustomIntegrator "/home/saifmulla/openmm/OpenMM/TestReferenceCustomIntegrator")
ADD_TEST(TestReferencePeriodicTorsionForce "/home/saifmulla/openmm/OpenMM/TestReferencePeriodicTorsionForce")
ADD_TEST(TestReferenceMonteCarloBarostat "/home/saifmulla/openmm/OpenMM/TestReferenceMonteCarloBarostat")
ADD_TEST(TestReferenceVirtualSites "/home/saifmulla/openmm/OpenMM/TestReferenceVirtualSites")
ADD_TEST(TestReferenceCustomNonbondedForce "/home/saifmulla/openmm/OpenMM/TestReferenceCustomNonbondedForce")
ADD_TEST(TestReferenceCustomBondForce "/home/saifmulla/openmm/OpenMM/TestReferenceCustomBondForce")
ADD_TEST(TestReferenceCMMotionRemover "/home/saifmulla/openmm/OpenMM/TestReferenceCMMotionRemover")
ADD_TEST(TestReferenceVerletIntegrator "/home/saifmulla/openmm/OpenMM/TestReferenceVerletIntegrator")
