# CMake generated Testfile for 
# Source directory: /home/saifmulla/openmm/OpenMM/platforms/opencl/tests
# Build directory: /home/saifmulla/openmm/OpenMM/platforms/opencl/tests
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(TestOpenCLVerletIntegrator "/home/saifmulla/openmm/OpenMM/TestOpenCLVerletIntegrator")
ADD_TEST(TestOpenCLMultipleForces "/home/saifmulla/openmm/OpenMM/TestOpenCLMultipleForces")
ADD_TEST(TestOpenCLPeriodicTorsionForce "/home/saifmulla/openmm/OpenMM/TestOpenCLPeriodicTorsionForce")
ADD_TEST(TestOpenCLMonteCarloBarostat "/home/saifmulla/openmm/OpenMM/TestOpenCLMonteCarloBarostat")
ADD_TEST(TestOpenCLSettle "/home/saifmulla/openmm/OpenMM/TestOpenCLSettle")
ADD_TEST(TestOpenCLNonbondedForce "/home/saifmulla/openmm/OpenMM/TestOpenCLNonbondedForce")
ADD_TEST(TestOpenCLCMAPTorsionForce "/home/saifmulla/openmm/OpenMM/TestOpenCLCMAPTorsionForce")
ADD_TEST(TestOpenCLFFT "/home/saifmulla/openmm/OpenMM/TestOpenCLFFT")
ADD_TEST(TestOpenCLRBTorsionForce "/home/saifmulla/openmm/OpenMM/TestOpenCLRBTorsionForce")
ADD_TEST(TestOpenCLHarmonicBondForce "/home/saifmulla/openmm/OpenMM/TestOpenCLHarmonicBondForce")
ADD_TEST(TestOpenCLBrownianIntegrator "/home/saifmulla/openmm/OpenMM/TestOpenCLBrownianIntegrator")
ADD_TEST(TestOpenCLCustomGBForce "/home/saifmulla/openmm/OpenMM/TestOpenCLCustomGBForce")
ADD_TEST(TestOpenCLRandom "/home/saifmulla/openmm/OpenMM/TestOpenCLRandom")
ADD_TEST(TestOpenCLLocalEnergyMinimizer "/home/saifmulla/openmm/OpenMM/TestOpenCLLocalEnergyMinimizer")
ADD_TEST(TestOpenCLGBSAOBCForce "/home/saifmulla/openmm/OpenMM/TestOpenCLGBSAOBCForce")
ADD_TEST(TestOpenCLNonbondForce2 "/home/saifmulla/openmm/OpenMM/TestOpenCLNonbondForce2")
ADD_TEST(TestOpenCLGBSAOBCForce2 "/home/saifmulla/openmm/OpenMM/TestOpenCLGBSAOBCForce2")
ADD_TEST(TestOpenCLCustomExternalForce "/home/saifmulla/openmm/OpenMM/TestOpenCLCustomExternalForce")
ADD_TEST(TestOpenCLCustomBondForce "/home/saifmulla/openmm/OpenMM/TestOpenCLCustomBondForce")
ADD_TEST(TestOpenCLCMMotionRemover "/home/saifmulla/openmm/OpenMM/TestOpenCLCMMotionRemover")
ADD_TEST(TestOpenCLCustomIntegrator "/home/saifmulla/openmm/OpenMM/TestOpenCLCustomIntegrator")
ADD_TEST(TestOpenCLAndersenThermostat "/home/saifmulla/openmm/OpenMM/TestOpenCLAndersenThermostat")
ADD_TEST(TestOpenCLLangevinIntegrator "/home/saifmulla/openmm/OpenMM/TestOpenCLLangevinIntegrator")
ADD_TEST(TestOpenCLCustomNonbondedForce "/home/saifmulla/openmm/OpenMM/TestOpenCLCustomNonbondedForce")
ADD_TEST(TestOpenCLSort "/home/saifmulla/openmm/OpenMM/TestOpenCLSort")
ADD_TEST(TestOpenCLVariableVerletIntegrator "/home/saifmulla/openmm/OpenMM/TestOpenCLVariableVerletIntegrator")
ADD_TEST(TestOpenCLCustomHbondForce "/home/saifmulla/openmm/OpenMM/TestOpenCLCustomHbondForce")
ADD_TEST(TestOpenCLVariableLangevinIntegrator "/home/saifmulla/openmm/OpenMM/TestOpenCLVariableLangevinIntegrator")
ADD_TEST(TestOpenCLCustomTorsionForce "/home/saifmulla/openmm/OpenMM/TestOpenCLCustomTorsionForce")
ADD_TEST(TestOpenCLHarmonicAngleForce "/home/saifmulla/openmm/OpenMM/TestOpenCLHarmonicAngleForce")
ADD_TEST(TestOpenCLCustomAngleForce "/home/saifmulla/openmm/OpenMM/TestOpenCLCustomAngleForce")
ADD_TEST(TestOpenCLVirtualSites "/home/saifmulla/openmm/OpenMM/TestOpenCLVirtualSites")
ADD_TEST(TestOpenCLEwald "/home/saifmulla/openmm/OpenMM/TestOpenCLEwald")
ADD_TEST(TestOpenCLVelocityVerletIntegrator "/home/saifmulla/openmm/OpenMM/TestOpenCLVelocityVerletIntegrator")
