#define __NV_CUBIN_HANDLE_STORAGE__ static
#include "crt/host_runtime.h"
#include "bbsort.fatbin.c"
static void __device_stub__Z10reduceSumDPfii(float *, int, int);
static void __device_stub__Z10reduceMaxDI4int2EvPT_ii(struct int2 *, int, int);
static void __device_stub__Z10reduceMinDI4int2EvPT_ii(struct int2 *, int, int);
static void __device_stub__Z14calDifferenceDI4int2EvPT_Pfi(struct int2 *, float *, int);
static void __device_stub__Z34assignElementToSlicesNearlySortedDI4int2EvPT_iPjS3_ffii(struct int2 *, int, unsigned *, unsigned *, float, float, int, int);
static void __device_stub__Z22assignElementToSlicesDI4int2EvPT_iPjS3_ffi(struct int2 *, int, unsigned *, unsigned *, float, float, int);
static void __device_stub__Z22assignElementToBucketDI4int2EvPT_S2_iPjff(struct int2 *, struct int2 *, int, unsigned *, float, float);
static void __device_stub__Z12bitonicSortDI4int2EvPT_(struct int2 *);
static void __nv_cudaEntityRegisterCallback(void **);
static void __sti____cudaRegisterAll_25_bbsort_compute_20_cpp1_ii_d2f2e07f(void) __attribute__((__constructor__));
static void __device_stub__Z10reduceSumDPfii(float *__par0, int __par1, int __par2){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaSetupArgSimple(__par2, 12UL);__cudaLaunch(((char *)((void ( *)(float *, int, int))reduceSumD)));}
# 64 "/home/saifmulla/openmm/OpenMM/platforms/cuda/./src/kernels//bbsort_kernel.cu"
static void reduceSumD( float *__cuda_0,int __cuda_1,int __cuda_2)
# 65 "/home/saifmulla/openmm/OpenMM/platforms/cuda/./src/kernels//bbsort_kernel.cu"
{__device_stub__Z10reduceSumDPfii( __cuda_0,__cuda_1,__cuda_2);
# 73 "/home/saifmulla/openmm/OpenMM/platforms/cuda/./src/kernels//bbsort_kernel.cu"
}
# 1 "bbsort.compute_12.cudafe1.stub.c"
static void __device_stub__Z10reduceMaxDI4int2EvPT_ii( struct int2 *__par0,  int __par1,  int __par2) {  __cudaSetupArgSimple(__par0, 0UL); __cudaSetupArgSimple(__par1, 8UL); __cudaSetupArgSimple(__par2, 12UL); __cudaLaunch(((char *)((void ( *)(struct int2 *, int, int))reduceMaxD<int2> ))); }
template<> __specialization_static void __wrapper__device_stub_reduceMaxD<int2>( struct int2 *&__cuda_0,int &__cuda_1,int &__cuda_2){__device_stub__Z10reduceMaxDI4int2EvPT_ii( __cuda_0,__cuda_1,__cuda_2);}
static void __device_stub__Z10reduceMinDI4int2EvPT_ii( struct int2 *__par0,  int __par1,  int __par2) {  __cudaSetupArgSimple(__par0, 0UL); __cudaSetupArgSimple(__par1, 8UL); __cudaSetupArgSimple(__par2, 12UL); __cudaLaunch(((char *)((void ( *)(struct int2 *, int, int))reduceMinD<int2> ))); }
template<> __specialization_static void __wrapper__device_stub_reduceMinD<int2>( struct int2 *&__cuda_0,int &__cuda_1,int &__cuda_2){__device_stub__Z10reduceMinDI4int2EvPT_ii( __cuda_0,__cuda_1,__cuda_2);}
static void __device_stub__Z14calDifferenceDI4int2EvPT_Pfi( struct int2 *__par0,  float *__par1,  int __par2) {  __cudaSetupArgSimple(__par0, 0UL); __cudaSetupArgSimple(__par1, 8UL); __cudaSetupArgSimple(__par2, 16UL); __cudaLaunch(((char *)((void ( *)(struct int2 *, float *, int))calDifferenceD<int2> ))); }
template<> __specialization_static void __wrapper__device_stub_calDifferenceD<int2>( struct int2 *&__cuda_0,float *&__cuda_1,int &__cuda_2){__device_stub__Z14calDifferenceDI4int2EvPT_Pfi( __cuda_0,__cuda_1,__cuda_2);}
static void __device_stub__Z34assignElementToSlicesNearlySortedDI4int2EvPT_iPjS3_ffii( struct int2 *__par0,  int __par1,  unsigned *__par2,  unsigned *__par3,  float __par4,  float __par5,  int __par6,  int __par7) {  __cudaSetupArgSimple(__par0, 0UL); __cudaSetupArgSimple(__par1, 8UL); __cudaSetupArgSimple(__par2, 16UL); __cudaSetupArgSimple(__par3, 24UL); __cudaSetupArgSimple(__par4, 32UL); __cudaSetupArgSimple(__par5, 36UL); __cudaSetupArgSimple(__par6, 40UL); __cudaSetupArgSimple(__par7, 44UL); __cudaLaunch(((char *)((void ( *)(struct int2 *, int, unsigned *, unsigned *, float, float, int, int))assignElementToSlicesNearlySortedD<int2> ))); }
template<> __specialization_static void __wrapper__device_stub_assignElementToSlicesNearlySortedD<int2>( struct int2 *&__cuda_0,int &__cuda_1,unsigned *&__cuda_2,unsigned *&__cuda_3,float &__cuda_4,float &__cuda_5,int &__cuda_6,int &__cuda_7){__device_stub__Z34assignElementToSlicesNearlySortedDI4int2EvPT_iPjS3_ffii( __cuda_0,__cuda_1,__cuda_2,__cuda_3,__cuda_4,__cuda_5,__cuda_6,__cuda_7);}
static void __device_stub__Z22assignElementToSlicesDI4int2EvPT_iPjS3_ffi( struct int2 *__par0,  int __par1,  unsigned *__par2,  unsigned *__par3,  float __par4,  float __par5,  int __par6) {  __cudaSetupArgSimple(__par0, 0UL); __cudaSetupArgSimple(__par1, 8UL); __cudaSetupArgSimple(__par2, 16UL); __cudaSetupArgSimple(__par3, 24UL); __cudaSetupArgSimple(__par4, 32UL); __cudaSetupArgSimple(__par5, 36UL); __cudaSetupArgSimple(__par6, 40UL); __cudaLaunch(((char *)((void ( *)(struct int2 *, int, unsigned *, unsigned *, float, float, int))assignElementToSlicesD<int2> ))); }
template<> __specialization_static void __wrapper__device_stub_assignElementToSlicesD<int2>( struct int2 *&__cuda_0,int &__cuda_1,unsigned *&__cuda_2,unsigned *&__cuda_3,float &__cuda_4,float &__cuda_5,int &__cuda_6){__device_stub__Z22assignElementToSlicesDI4int2EvPT_iPjS3_ffi( __cuda_0,__cuda_1,__cuda_2,__cuda_3,__cuda_4,__cuda_5,__cuda_6);}
static void __device_stub__Z22assignElementToBucketDI4int2EvPT_S2_iPjff( struct int2 *__par0,  struct int2 *__par1,  int __par2,  unsigned *__par3,  float __par4,  float __par5) {  __cudaSetupArgSimple(__par0, 0UL); __cudaSetupArgSimple(__par1, 8UL); __cudaSetupArgSimple(__par2, 16UL); __cudaSetupArgSimple(__par3, 24UL); __cudaSetupArgSimple(__par4, 32UL); __cudaSetupArgSimple(__par5, 36UL); __cudaLaunch(((char *)((void ( *)(struct int2 *, struct int2 *, int, unsigned *, float, float))assignElementToBucketD<int2> ))); }
template<> __specialization_static void __wrapper__device_stub_assignElementToBucketD<int2>( struct int2 *&__cuda_0,struct int2 *&__cuda_1,int &__cuda_2,unsigned *&__cuda_3,float &__cuda_4,float &__cuda_5){__device_stub__Z22assignElementToBucketDI4int2EvPT_S2_iPjff( __cuda_0,__cuda_1,__cuda_2,__cuda_3,__cuda_4,__cuda_5);}
static void __device_stub__Z12bitonicSortDI4int2EvPT_( struct int2 *__par0) {  __cudaSetupArgSimple(__par0, 0UL); __cudaLaunch(((char *)((void ( *)(struct int2 *))bitonicSortD<int2> ))); }
template<> __specialization_static void __wrapper__device_stub_bitonicSortD<int2>( struct int2 *&__cuda_0){__device_stub__Z12bitonicSortDI4int2EvPT_( __cuda_0);}
static void __nv_cudaEntityRegisterCallback( void **__T257) {  __nv_dummy_param_ref(__T257); __cudaRegisterEntry(__T257, ((void ( *)(struct int2 *))bitonicSortD<int2> ), _Z12bitonicSortDI4int2EvPT_, (-1)); __cudaRegisterEntry(__T257, ((void ( *)(struct int2 *, struct int2 *, int, unsigned *, float, float))assignElementToBucketD<int2> ), _Z22assignElementToBucketDI4int2EvPT_S2_iPjff, (-1)); __cudaRegisterEntry(__T257, ((void ( *)(struct int2 *, int, unsigned *, unsigned *, float, float, int))assignElementToSlicesD<int2> ), _Z22assignElementToSlicesDI4int2EvPT_iPjS3_ffi, (-1)); __cudaRegisterEntry(__T257, ((void ( *)(struct int2 *, int, unsigned *, unsigned *, float, float, int, int))assignElementToSlicesNearlySortedD<int2> ), _Z34assignElementToSlicesNearlySortedDI4int2EvPT_iPjS3_ffii, (-1)); __cudaRegisterEntry(__T257, ((void ( *)(struct int2 *, float *, int))calDifferenceD<int2> ), _Z14calDifferenceDI4int2EvPT_Pfi, (-1)); __cudaRegisterEntry(__T257, ((void ( *)(struct int2 *, int, int))reduceMinD<int2> ), _Z10reduceMinDI4int2EvPT_ii, (-1)); __cudaRegisterEntry(__T257, ((void ( *)(struct int2 *, int, int))reduceMaxD<int2> ), _Z10reduceMaxDI4int2EvPT_ii, (-1)); __cudaRegisterEntry(__T257, ((void ( *)(float *, int, int))reduceSumD), _Z10reduceSumDPfii, (-1)); __cudaRegisterGlobalTexture(__T257, __text_var(tBucketSizes,tBucketSizes), 1, 0, 0); __cudaRegisterGlobalTexture(__T257, __text_var(tBucketOffsets,tBucketOffsets), 1, 0, 0); __cudaRegisterGlobalTexture(__T257, __text_var(tBucketOfSlices,tBucketOfSlices), 1, 0, 0); __cudaRegisterGlobalTexture(__T257, __text_var(tSliceOffsetInBucket,tSliceOffsetInBucket), 1, 0, 0); }
static void __sti____cudaRegisterAll_25_bbsort_compute_20_cpp1_ii_d2f2e07f(void) {  __cudaRegisterBinary(__nv_cudaEntityRegisterCallback);  }
