# CMake generated Testfile for 
# Source directory: /home/saifmulla/openmm/OpenMM/platforms/opencl/tests
# Build directory: /home/saifmulla/openmm/OpenMM/buildd/platforms/opencl/tests
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(TestOpenCLVerletIntegrator "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLVerletIntegrator")
ADD_TEST(TestOpenCLMultipleForces "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLMultipleForces")
ADD_TEST(TestOpenCLPeriodicTorsionForce "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLPeriodicTorsionForce")
ADD_TEST(TestOpenCLMonteCarloBarostat "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLMonteCarloBarostat")
ADD_TEST(TestOpenCLSettle "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLSettle")
ADD_TEST(TestOpenCLNonbondedForce "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLNonbondedForce")
ADD_TEST(TestOpenCLCMAPTorsionForce "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLCMAPTorsionForce")
ADD_TEST(TestOpenCLFFT "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLFFT")
ADD_TEST(TestOpenCLRBTorsionForce "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLRBTorsionForce")
ADD_TEST(TestOpenCLHarmonicBondForce "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLHarmonicBondForce")
ADD_TEST(TestOpenCLBrownianIntegrator "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLBrownianIntegrator")
ADD_TEST(TestOpenCLCustomGBForce "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLCustomGBForce")
ADD_TEST(TestOpenCLRandom "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLRandom")
ADD_TEST(TestOpenCLLocalEnergyMinimizer "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLLocalEnergyMinimizer")
ADD_TEST(TestOpenCLGBSAOBCForce "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLGBSAOBCForce")
ADD_TEST(TestOpenCLNonbondForce2 "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLNonbondForce2")
ADD_TEST(TestOpenCLGBSAOBCForce2 "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLGBSAOBCForce2")
ADD_TEST(TestOpenCLCustomExternalForce "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLCustomExternalForce")
ADD_TEST(TestOpenCLCustomBondForce "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLCustomBondForce")
ADD_TEST(TestOpenCLCMMotionRemover "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLCMMotionRemover")
ADD_TEST(TestOpenCLCustomIntegrator "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLCustomIntegrator")
ADD_TEST(TestOpenCLAndersenThermostat "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLAndersenThermostat")
ADD_TEST(TestOpenCLLangevinIntegrator "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLLangevinIntegrator")
ADD_TEST(TestOpenCLCustomNonbondedForce "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLCustomNonbondedForce")
ADD_TEST(TestOpenCLSort "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLSort")
ADD_TEST(TestOpenCLVariableVerletIntegrator "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLVariableVerletIntegrator")
ADD_TEST(TestOpenCLCustomHbondForce "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLCustomHbondForce")
ADD_TEST(TestOpenCLVariableLangevinIntegrator "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLVariableLangevinIntegrator")
ADD_TEST(TestOpenCLCustomTorsionForce "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLCustomTorsionForce")
ADD_TEST(TestOpenCLHarmonicAngleForce "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLHarmonicAngleForce")
ADD_TEST(TestOpenCLCustomAngleForce "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLCustomAngleForce")
ADD_TEST(TestOpenCLVirtualSites "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLVirtualSites")
ADD_TEST(TestOpenCLEwald "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLEwald")
ADD_TEST(TestOpenCLVelocityVerletIntegrator "/home/saifmulla/openmm/OpenMM/buildd/TestOpenCLVelocityVerletIntegrator")
